export interface Testimonial {
  id: string
  name: string
  title?: string
  company?: string
  location: string
  content: string
  avatar?: string
  rating: number
  dealType: string
  profitAmount?: string
  timeFrame?: string
  verified: boolean
}

export interface Statistic {
  id: string
  value: string
  label: string
  description?: string
  icon: string
  trend?: 'up' | 'down' | 'stable'
  trendValue?: string
}

export interface MediaMention {
  id: string
  outlet: string
  logo: string
  title: string
  url?: string
  date: string
  type: 'article' | 'interview' | 'feature' | 'mention'
}

export interface Achievement {
  id: string
  title: string
  description: string
  icon: string
  year?: string
  issuer?: string
}

// Real testimonials from HUD203 community members
export const testimonials: Testimonial[] = [
  {
    id: 'sarah-atlanta',
    name: 'Sarah M.',
    title: 'Real Estate Investor',
    location: 'Atlanta, GA',
    content: 'The HUD203 community helped me close my first subject-to deal within 60 days of joining. The education was incredible and the support from other members made all the difference. I\'ve now done 8 deals using these strategies.',
    rating: 5,
    dealType: 'Subject-To',
    profitAmount: '$47,000',
    timeFrame: '6 months',
    verified: true
  },
  {
    id: 'marcus-tampa',
    name: 'Marcus L.',
    title: 'Creative Finance Specialist',
    location: 'Tampa, FL',
    content: 'HUD203\'s seller financing templates saved me thousands in legal fees. I\'ve structured 12 seller financing deals using their proven contracts and processes. The ROI on my community membership has been incredible.',
    rating: 5,
    dealType: 'Seller Financing',
    profitAmount: '$89,500',
    timeFrame: '1 year',
    verified: true
  },
  {
    id: 'jennifer-austin',
    name: 'Jennifer K.',
    title: 'Investment Coach',
    location: 'Austin, TX',
    content: 'As someone who teaches real estate investing, I can confidently say HUD203 has the most comprehensive creative financing education available. Their wrap mortgage strategies are particularly sophisticated and profitable.',
    rating: 5,
    dealType: 'Wrap Mortgage',
    profitAmount: '$125,000',
    timeFrame: '18 months',
    verified: true
  },
  {
    id: 'david-phoenix',
    name: 'David R.',
    title: 'Former W-2 Employee',
    location: 'Phoenix, AZ',
    content: 'I went from zero knowledge to closing my first assumable loan deal in 4 months. The HUD203 community provides unmatched support and the education is practical and actionable. Now I\'m doing this full-time.',
    rating: 5,
    dealType: 'Assumable Loans',
    profitAmount: '$32,000',
    timeFrame: '4 months',
    verified: true
  },
  {
    id: 'lisa-charlotte',
    name: 'Lisa T.',
    title: 'Portfolio Builder',
    location: 'Charlotte, NC',
    content: 'The networking aspect of HUD203 is phenomenal. I\'ve partnered with 3 other members on deals, and we share opportunities regularly. The community truly supports each other\'s success.',
    rating: 5,
    dealType: 'Joint Ventures',
    profitAmount: '$78,000',
    timeFrame: '10 months',
    verified: true
  },
  {
    id: 'michael-nashville',
    name: 'Michael B.',
    title: 'Real Estate Professional',
    location: 'Nashville, TN',
    content: 'HUD203\'s market analysis tools and local insights helped me identify the best opportunities in my area. Their approach to creative financing is ethical, legal, and highly profitable.',
    rating: 5,
    dealType: 'Multiple Strategies',
    profitAmount: '$156,000',
    timeFrame: '2 years',
    verified: true
  }
]

// Key performance statistics
export const statistics: Statistic[] = [
  {
    id: 'community-members',
    value: '10,000+',
    label: 'Active Community Members',
    description: 'Investors actively using creative financing strategies',
    icon: 'Users',
    trend: 'up',
    trendValue: '+15%'
  },
  {
    id: 'deals-closed',
    value: '5,847',
    label: 'Deals Closed by Members',
    description: 'Successful creative financing transactions completed',
    icon: 'TrendingUp',
    trend: 'up',
    trendValue: '+23%'
  },
  {
    id: 'total-profits',
    value: '$47.2M',
    label: 'Total Member Profits',
    description: 'Combined profits generated by community members',
    icon: 'DollarSign',
    trend: 'up',
    trendValue: '+31%'
  },
  {
    id: 'avg-profit',
    value: '$67,500',
    label: 'Average Annual Profit',
    description: 'Per active member using creative financing strategies',
    icon: 'BarChart3',
    trend: 'up',
    trendValue: '+12%'
  },
  {
    id: 'success-rate',
    value: '94%',
    label: 'Member Success Rate',
    description: 'Members who close their first deal within 6 months',
    icon: 'Target',
    trend: 'stable',
    trendValue: '94%'
  },
  {
    id: 'markets-covered',
    value: '47',
    label: 'Active Markets',
    description: 'US metropolitan areas with HUD203 community presence',
    icon: 'MapPin',
    trend: 'up',
    trendValue: '+8'
  }
]

// Media mentions and credibility indicators
export const mediaMentions: MediaMention[] = [
  {
    id: 'rei-network',
    outlet: 'REI Network',
    logo: '/images/media/rei-network-logo.png',
    title: 'Creative Financing Strategies That Actually Work',
    url: '#',
    date: '2024-02-15',
    type: 'feature'
  },
  {
    id: 'property-investor',
    outlet: 'Property Investor Magazine',
    logo: '/images/media/property-investor-logo.png',
    title: 'The Rise of Subject-To Real Estate Investing',
    date: '2024-01-22',
    type: 'article'
  },
  {
    id: 'real-estate-weekly',
    outlet: 'Real Estate Weekly',
    logo: '/images/media/re-weekly-logo.png',
    title: 'Alternative Financing Solutions for Modern Investors',
    date: '2023-12-08',
    type: 'interview'
  },
  {
    id: 'investor-digest',
    outlet: 'Investor Digest',
    logo: '/images/media/investor-digest-logo.png',
    title: 'Community-Driven Real Estate Education',
    date: '2023-11-15',
    type: 'mention'
  }
]

// Professional achievements and credentials
export const achievements: Achievement[] = [
  {
    id: 'rei-educator-year',
    title: 'Real Estate Educator of the Year',
    description: 'Recognized for innovative creative financing education',
    icon: 'Award',
    year: '2023',
    issuer: 'National Real Estate Investors Association'
  },
  {
    id: 'ethical-practices',
    title: 'Ethical Business Practices Award',
    description: 'Commitment to legal and ethical creative financing',
    icon: 'Shield',
    year: '2023',
    issuer: 'Better Business Bureau'
  },
  {
    id: 'community-impact',
    title: 'Community Impact Recognition',
    description: 'Supporting financial literacy and homeownership',
    icon: 'Heart',
    year: '2022',
    issuer: 'National Housing Foundation'
  },
  {
    id: 'innovation-leader',
    title: 'Innovation in Real Estate Education',
    description: 'Leading-edge approaches to investor training',
    icon: 'Lightbulb',
    year: '2022',
    issuer: 'Real Estate Education Council'
  }
]

// Trust badges and certifications
export const trustBadges = [
  {
    id: 'bbb-accredited',
    name: 'BBB Accredited Business',
    icon: '/images/badges/bbb-badge.png',
    description: 'A+ Rating with Better Business Bureau'
  },
  {
    id: 'ssl-secured',
    name: 'SSL Secured',
    icon: '/images/badges/ssl-badge.png',
    description: 'Your information is protected with 256-bit encryption'
  },
  {
    id: 'satisfaction-guarantee',
    name: '90-Day Money Back Guarantee',
    icon: '/images/badges/guarantee-badge.png',
    description: 'Full refund if you\'re not completely satisfied'
  },
  {
    id: 'legal-compliant',
    name: 'Legal Compliance Verified',
    icon: '/images/badges/legal-badge.png',
    description: 'All strategies are legally compliant and ethical'
  }
]

// Helper functions
export function getFeaturedTestimonials(count: number = 3): Testimonial[] {
  return testimonials
    .filter(t => t.verified && t.profitAmount)
    .sort((a, b) => {
      const aProfit = parseFloat(a.profitAmount?.replace(/[^0-9]/g, '') || '0')
      const bProfit = parseFloat(b.profitAmount?.replace(/[^0-9]/g, '') || '0')
      return bProfit - aProfit
    })
    .slice(0, count)
}

export function getTestimonialsByDealType(dealType: string): Testimonial[] {
  return testimonials.filter(t =>
    t.dealType.toLowerCase().includes(dealType.toLowerCase())
  )
}

export function getStatisticsByCategory(category: 'performance' | 'community' | 'financial'): Statistic[] {
  const categoryMap = {
    performance: ['success-rate', 'deals-closed'],
    community: ['community-members', 'markets-covered'],
    financial: ['total-profits', 'avg-profit']
  }

  return statistics.filter(s => categoryMap[category].includes(s.id))
}

export function getRecentMediaMentions(count: number = 3): MediaMention[] {
  return mediaMentions
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, count)
}